<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        Service::insert([
            ['name' => 'Khám nam khoa', 'description' => 'Dịch vụ khám nam khoa chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 565975],
            ['name' => 'Khám nhi', 'description' => 'Dịch vụ khám nhi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 367299],
            ['name' => 'Khám thần kinh', 'description' => 'Dịch vụ khám thần kinh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 879702],
            ['name' => 'Khám dị ứng da', 'description' => 'Dịch vụ khám dị ứng da chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 945147],
            ['name' => 'Khám men gan', 'description' => 'Dịch vụ khám men gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 989590],
            ['name' => 'Khám kiểm tra mắt', 'description' => 'Dịch vụ khám kiểm tra mắt chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 197480],
            ['name' => 'Khám phổi lao', 'description' => 'Dịch vụ khám phổi lao chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 258339],
            ['name' => 'Khám định kỳ nhân viên', 'description' => 'Dịch vụ khám định kỳ nhân viên chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 505290],
            ['name' => 'Khám nội soi', 'description' => 'Dịch vụ khám nội soi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 538485],
            ['name' => 'Khám cơ xương', 'description' => 'Dịch vụ khám cơ xương chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 275977],
            ['name' => 'Khám sản phụ khoa', 'description' => 'Dịch vụ khám sản phụ khoa chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 706961],
            ['name' => 'Khám da liễu tổng quát', 'description' => 'Dịch vụ khám da liễu tổng quát chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 105117],
            ['name' => 'Khám cột sống', 'description' => 'Dịch vụ khám cột sống chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 752111],
            ['name' => 'Khám tim mạch nhi', 'description' => 'Dịch vụ khám tim mạch nhi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 330984],
            ['name' => 'Khám huyết học', 'description' => 'Dịch vụ khám huyết học chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 132483],
            ['name' => 'Khám tổng quát nam', 'description' => 'Dịch vụ khám tổng quát nam chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 978975],
            ['name' => 'Khám mắt', 'description' => 'Dịch vụ khám mắt chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 696670],
            ['name' => 'Khám tiết niệu', 'description' => 'Dịch vụ khám tiết niệu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 309361],
            ['name' => 'Khám tâm lý', 'description' => 'Dịch vụ khám tâm lý chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 472145],
            ['name' => 'Khám phổi chuyên sâu', 'description' => 'Dịch vụ khám phổi chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 661183],
            ['name' => 'Khám men gan', 'description' => 'Dịch vụ khám men gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 560235],
            ['name' => 'Khám bệnh nhân cao huyết áp', 'description' => 'Dịch vụ khám bệnh nhân cao huyết áp chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 164816],
            ['name' => 'Khám tai mũi họng nhi', 'description' => 'Dịch vụ khám tai mũi họng nhi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 491602],
            ['name' => 'Khám tai mũi họng', 'description' => 'Dịch vụ khám tai mũi họng chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 948798],
            ['name' => 'Khám men gan', 'description' => 'Dịch vụ khám men gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 978370],
            ['name' => 'Khám da đầu', 'description' => 'Dịch vụ khám da đầu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 185836],
            ['name' => 'Khám gan', 'description' => 'Dịch vụ khám gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 624642],
            ['name' => 'Khám tiền sử bệnh', 'description' => 'Dịch vụ khám tiền sử bệnh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 989632],
            ['name' => 'Khám tim mạch', 'description' => 'Dịch vụ khám tim mạch chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 287203],
            ['name' => 'Khám viêm khớp', 'description' => 'Dịch vụ khám viêm khớp chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 904382],
            ['name' => 'Khám hệ miễn dịch', 'description' => 'Dịch vụ khám hệ miễn dịch chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 572911],
            ['name' => 'Khám mắt chuyên sâu', 'description' => 'Dịch vụ khám mắt chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 758073],
            ['name' => 'Khám thần kinh', 'description' => 'Dịch vụ khám thần kinh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 598264],
            ['name' => 'Khám dị ứng da', 'description' => 'Dịch vụ khám dị ứng da chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 526707],
            ['name' => 'Khám đầu gối', 'description' => 'Dịch vụ khám đầu gối chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 126406],
            ['name' => 'Khám men gan', 'description' => 'Dịch vụ khám men gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 498162],
            ['name' => 'Khám hệ thần kinh trung ương', 'description' => 'Dịch vụ khám hệ thần kinh trung ương chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 885596],
            ['name' => 'Khám sơ sinh', 'description' => 'Dịch vụ khám sơ sinh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 799842],
            ['name' => 'Khám tim mạch nhi', 'description' => 'Dịch vụ khám tim mạch nhi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 678355],
            ['name' => 'Khám sản phụ khoa', 'description' => 'Dịch vụ khám sản phụ khoa chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 925607],
            ['name' => 'Khám cơ thể tổng quát', 'description' => 'Dịch vụ khám cơ thể tổng quát chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 370990],
            ['name' => 'Khám tiêu hóa chuyên sâu', 'description' => 'Dịch vụ khám tiêu hóa chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 766585],
            ['name' => 'Khám da đầu chuyên sâu', 'description' => 'Dịch vụ khám da đầu chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 874553],
            ['name' => 'Khám ngoại khoa', 'description' => 'Dịch vụ khám ngoại khoa chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 555155],
            ['name' => 'Khám viêm phổi', 'description' => 'Dịch vụ khám viêm phổi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 380145],
            ['name' => 'Khám tiêu hóa chuyên sâu', 'description' => 'Dịch vụ khám tiêu hóa chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 406479],
            ['name' => 'Khám hô hấp tổng quát', 'description' => 'Dịch vụ khám hô hấp tổng quát chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 743673],
            ['name' => 'Khám nhi', 'description' => 'Dịch vụ khám nhi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 189403],
            ['name' => 'Khám gan mật', 'description' => 'Dịch vụ khám gan mật chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 876083],
            ['name' => 'Khám kiểm tra mắt', 'description' => 'Dịch vụ khám kiểm tra mắt chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 494769],
            ['name' => 'Khám xương khớp', 'description' => 'Dịch vụ khám xương khớp chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 823928],
            ['name' => 'Khám định kỳ nhân viên', 'description' => 'Dịch vụ khám định kỳ nhân viên chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 230983],
            ['name' => 'Khám tai mũi họng', 'description' => 'Dịch vụ khám tai mũi họng chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 870998],
            ['name' => 'Khám phổi', 'description' => 'Dịch vụ khám phổi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 128215],
            ['name' => 'Khám mắt', 'description' => 'Dịch vụ khám mắt chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 289962],
            ['name' => 'Khám tâm thần', 'description' => 'Dịch vụ khám tâm thần chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 753291],
            ['name' => 'Khám hô hấp tổng quát', 'description' => 'Dịch vụ khám hô hấp tổng quát chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 499072],
            ['name' => 'Khám đau lưng', 'description' => 'Dịch vụ khám đau lưng chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 151945],
            ['name' => 'Khám định kỳ học sinh', 'description' => 'Dịch vụ khám định kỳ học sinh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 926329],
            ['name' => 'Khám nhi', 'description' => 'Dịch vụ khám nhi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 770147],
            ['name' => 'Khám cơ thể tổng quát', 'description' => 'Dịch vụ khám cơ thể tổng quát chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 452433],
            ['name' => 'Khám dạ dày', 'description' => 'Dịch vụ khám dạ dày chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 902780],
            ['name' => 'Khám men gan', 'description' => 'Dịch vụ khám men gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 936272],
            ['name' => 'Khám kiểm tra sức khỏe', 'description' => 'Dịch vụ khám kiểm tra sức khỏe chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 707868],
            ['name' => 'Khám loãng xương', 'description' => 'Dịch vụ khám loãng xương chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 406400],
            ['name' => 'Khám sơ sinh', 'description' => 'Dịch vụ khám sơ sinh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 596602],
            ['name' => 'Khám nội tiết chuyên sâu', 'description' => 'Dịch vụ khám nội tiết chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 252009],
            ['name' => 'Khám hệ miễn dịch', 'description' => 'Dịch vụ khám hệ miễn dịch chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 268929],
            ['name' => 'Khám viêm khớp dạng thấp', 'description' => 'Dịch vụ khám viêm khớp dạng thấp chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 987164],
            ['name' => 'Khám kiểm tra sức khỏe', 'description' => 'Dịch vụ khám kiểm tra sức khỏe chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 169473],
            ['name' => 'Khám dạ dày nội soi', 'description' => 'Dịch vụ khám dạ dày nội soi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 288735],
            ['name' => 'Khám mắt', 'description' => 'Dịch vụ khám mắt chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 619125],
            ['name' => 'Khám dị ứng', 'description' => 'Dịch vụ khám dị ứng chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 978931],
            ['name' => 'Khám cổ tay', 'description' => 'Dịch vụ khám cổ tay chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 515281],
            ['name' => 'Khám sinh lý', 'description' => 'Dịch vụ khám sinh lý chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 410458],
            ['name' => 'Khám tâm thần', 'description' => 'Dịch vụ khám tâm thần chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 882934],
            ['name' => 'Khám sức khỏe lái xe', 'description' => 'Dịch vụ khám sức khỏe lái xe chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 189571],
            ['name' => 'Khám sản phụ khoa', 'description' => 'Dịch vụ khám sản phụ khoa chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 227689],
            ['name' => 'Khám nội tiết chuyên sâu', 'description' => 'Dịch vụ khám nội tiết chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 912033],
            ['name' => 'Khám đau vai gáy', 'description' => 'Dịch vụ khám đau vai gáy chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 571268],
            ['name' => 'Khám tim mạch', 'description' => 'Dịch vụ khám tim mạch chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 827373],
            ['name' => 'Khám da chuyên sâu', 'description' => 'Dịch vụ khám da chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 441190],
            ['name' => 'Khám viêm xoang', 'description' => 'Dịch vụ khám viêm xoang chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 256777],
            ['name' => 'Khám định kỳ nhân viên', 'description' => 'Dịch vụ khám định kỳ nhân viên chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 510357],
            ['name' => 'Khám men gan', 'description' => 'Dịch vụ khám men gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 731562],
            ['name' => 'Khám mắt chuyên sâu', 'description' => 'Dịch vụ khám mắt chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 763384],
            ['name' => 'Khám gan', 'description' => 'Dịch vụ khám gan chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 396527],
            ['name' => 'Khám mắt chuyên sâu', 'description' => 'Dịch vụ khám mắt chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 894360],
            ['name' => 'Khám dị ứng', 'description' => 'Dịch vụ khám dị ứng chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 949908],
            ['name' => 'Khám ung bướu', 'description' => 'Dịch vụ khám ung bướu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 892049],
            ['name' => 'Khám tiền sử bệnh', 'description' => 'Dịch vụ khám tiền sử bệnh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 106842],
            ['name' => 'Khám tổng quát nam', 'description' => 'Dịch vụ khám tổng quát nam chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 214466],
            ['name' => 'Khám răng trẻ em', 'description' => 'Dịch vụ khám răng trẻ em chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 819732],
            ['name' => 'Khám khớp háng', 'description' => 'Dịch vụ khám khớp háng chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 809664],
            ['name' => 'Khám nội khoa', 'description' => 'Dịch vụ khám nội khoa chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 713075],
            ['name' => 'Khám viêm da', 'description' => 'Dịch vụ khám viêm da chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 555425],
            ['name' => 'Khám nội tiết chuyên sâu', 'description' => 'Dịch vụ khám nội tiết chuyên sâu chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 283270],
            ['name' => 'Khám xương khớp', 'description' => 'Dịch vụ khám xương khớp chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 240155],
            ['name' => 'Khám nội thần kinh', 'description' => 'Dịch vụ khám nội thần kinh chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 405671],
            ['name' => 'Khám dạ dày nội soi', 'description' => 'Dịch vụ khám dạ dày nội soi chất lượng cao với đội ngũ bác sĩ chuyên nghiệp.', 'price' => 929377],
        ]);
    }
}
